### ISSUE TITLE
作者你好，我在复现您代码的过程中，运行trainer.py中的代码后出现了以下错误。请问您方便告知我一下如何解决吗？

### ISSUE THREAD

**Issue by lh5533223** [DEAL-US/RL-KG#1]
running integrity checks
No embeddings have been generated for _utils
datafolder is: E:\lh\SpaceRL-KG-master/datasets/COUNTRIES
generating embeddings for dataset COUNTRIES and models ['TransE_l2']
Selected embedding TransE_l2 is already generated for COUNTRIES dataset, if you want to regenerate use the regenerate boolean option
calculating embedding minimums and maximums...
100%|██████████| 4/4 [00:00<00:00, 4011.77it/s]
100%|██████████| 271/271 [00:00<00:00, 7356.62it/s]
triples: 1159, nodes:271, edges:2587
restoring model...
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer last_lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer last_lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer last_lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
Running episodes for: COUNTRIES-TransE_l2:   0%|          | 0/231800 [00:00<?, ?it/s]
running for 231800 iterations
Traceback (most recent call last):
  File "E:/lh/SpaceRL-KG-master/model/trainer.py", line 377, in <module>
    main(True)
  File "E:/lh/SpaceRL-KG-master/model/trainer.py", line 372, in main
    hasFinished = m.run()
  File "E:/lh/SpaceRL-KG-master/model/trainer.py", line 217, in run
    action, observation, reward, max_rew = self.agent.select_action()
  File "E:\lh\SpaceRL-KG-master\model\agent.py", line 579, in select_action
    inputs, rewards = self.get_inputs_and_rewards()
  File "E:\lh\SpaceRL-KG-master\model\agent.py", line 479, in get_inputs_and_rewards
    self.get_next_state_rewards(it)
  File "E:\lh\SpaceRL-KG-master\model\agent.py", line 357, in get_next_state_rewards
    encoded_action = self.encode_action(action_taken[0], action_taken[1])
  File "E:\lh\SpaceRL-KG-master\model\agent.py", line 339, in encode_action
    rel_emb = self.relation_emb[chosen_rel]
KeyError: '\xacneighborOf'

**Comment by lh5533223** [comment]
你好，我在Windows系统上部署好该代码的环境。屡次调试始终出现：KeyError: '¬neighborOf'这个错误。我怀疑是这个¬否定符号的编码格式问题。请问我该如何解决呀？
